### PR TITLE
Genes2weights

### LINKED ISSUE #14: Passing genes to neurons weights

### PR DESCRIPTION
**Pull request by VictorCadix**
Closes #14

### CODE REVIEW

**Comment by VictorCadix** [comment]
Issue: "vector subscript out of range" when calling the function.

**Comment by VictorCadix** [comment]
Now it should be good.

**Review by Raul6469 — APPROVED** [review]
Ça me semble bien, je te fais confiance 😅

**Comment by VictorCadix** [comment]
OK, je le merge.

**Pull request merged**
